"""agregar isbn a libros

Revision ID: f36f9c05bd1b
Revises: 9c672b59ecd6
Create Date: 2026-09-03 22:08:24.572852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36f9c05bd1b'
down_revision: Union[str, Sequence[str], None] = '9c672b59ecd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libros', sa.Column('isbn', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'libros', ['isbn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'libros', type_='unique')
    op.drop_column('libros', 'isbn')
    # ### end Alembic commands ###
